//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoProveedor
    {
        public int IdContactoProveedor { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Correo { get; set; }
        public Nullable<int> IdEstadoSistema { get; set; }
        public Nullable<int> IdProveedor { get; set; }
    
        public virtual EstadoSistema EstadoSistema { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
