//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(InventarioProductoMetadata))]
    public partial class InventarioProducto
    {
        public int IdInventario { get; set; }
        public int IdProducto { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> StockMinimo { get; set; }
        public string Estante { get; set; }
        public Nullable<int> IdEstadoSistema { get; set; }
    
        public virtual EstadoSistema EstadoSistema { get; set; }
        public virtual Inventario Inventario { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
