//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(MotivoMovimientoMetadata))]
    public partial class MotivoMovimiento
    {
        public int IdMotivoMovimiento { get; set; }
        public string Descripcion { get; set; }
    
        public virtual RegistroMovimiento RegistroMovimiento { get; set; }
    }
}
