//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.CalificacionUsuario = new HashSet<CalificacionUsuario>();
            this.Pedido = new HashSet<Pedido>();
            this.RegistroMovimiento = new HashSet<RegistroMovimiento>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Contra { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdEstadoSistema { get; set; }
        public Nullable<int> IdTipoUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalificacionUsuario> CalificacionUsuario { get; set; }
        public virtual EstadoSistema EstadoSistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroMovimiento> RegistroMovimiento { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
